<?php

namespace Drupal\bank_consult\TypedData;

use Drupal\Core\TypedData\TraversableTypedDataInterface;
use Drupal\Core\TypedData\TypedData;

class CustomIntegerDefinition extends TypedData {



  public static function createInstance($definition, $name = NULL, TraversableTypedDataInterface $parent = NULL) {
    return parent::createInstance($definition, $name, $parent); // TODO: Change the autogenerated stub
  }

}
