<?php

namespace Drupal\bank_consult\Plugin\DataType;

use Drupal\Core\StringTranslation\TranslationInterface;
use Drupal\Core\TypedData\Plugin\DataType\IntegerData;

/**
 * Defines a custom integer data type.
 *
 * @DataType(
 *   id = "custom_integer",
 *   label = @Translation("Custom Integer"),
 * )
 */
class CustomInteger extends IntegerData {

  public function getValue() {

    return (string) $this->value;
//    return parent::getValue(); // TODO: Change the autogenerated stub
  }



  //*   definition_class = "\Drupal\bank_consult\TypedData\CustomIntegerDefinition"


  // You can add custom methods and logic specific to your integer data type here.
}
