<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\RendererInterface;
use Drupal\mm_email\Form\CustomEmailsConfigForm;
use Symfony\Component\DependencyInjection\ContainerInterface;

class MyForm extends CustomEmailsConfigForm {

  protected $render;



  public static function create(ContainerInterface $container) {
    $instance = parent::create($container);
    $instance->render = $container->get('renderer');
    return $instance;
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}