<?php

namespace Drupal\bank_consult_advertiser\Entity\Controller;

use Drupal\bank_consult_advertiser\Entity\Advertiser;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityViewBuilder;
use Drupal\Core\Render\Element\Link;
use Drupal\Core\Security\DoTrustedCallbackTrait;
use Drupal\Core\Security\TrustedCallbackInterface;
use Drupal\node\NodeInterface;

class AdvertiserViewBuilder extends EntityViewBuilder {

  protected function addContextualLinks(array &$build, EntityInterface $entity) {
    parent::addContextualLinks($build, $entity);
    /** @var \Drupal\Core\Menu\ContextualLinkManagerInterface $contextual_manager */
    $contextual_manager = \Drupal::service('plugin.manager.menu.contextual_link');

    $plugins = $contextual_manager->getContextualLinkPluginsByGroup('advertiser');
    foreach ($plugins as $plugin_id => $plugin) {
      if (!in_array($entity->bundle(), $plugin['appears_on_bundles'])) {
        unset($build['#contextual_links']);
      }
    }
    // TODO: Change the autogenerated stub
  }




  //  public function buildComponents(array &$build, array $entities, array $displays, $view_mode) {
  //    /** @var \Drupal\node\NodeInterface[] $entities */
  //    if (empty($entities)) {
  //      return;
  //    }
  //
  //    parent::buildComponents($build, $entities, $displays, $view_mode);
  //
  //    foreach ($entities as $id => $entity) {
  //      $bundle = $entity->bundle();
  //      $display = $displays[$bundle];
  //
  //      if ($display->getComponent('links')) {
  //        $build[$id]['links'] = [
  //          '#lazy_builder' => [
  //            static::class . '::renderLinks',
  //            [
  //              $entity->id(),
  //              $view_mode,
  //            ],
  //          ],
  //        ];
  //      }
  //
  //    }
  //  }

  //  public static function renderLinks($advertiser_entity_id, $view_mode) {
  //    $links = [
  //      '#theme' => 'links__node',
  //      '#pre_render' => [[Link::class, 'preRenderLinks']],
  //      '#attributes' => ['class' => ['links', 'inline']],
  //    ];
  //
  ////    if (!$is_in_preview) {
  ////      $storage = \Drupal::entityTypeManager()->getStorage('node');
  ////      /** @var \Drupal\node\NodeInterface $revision */
  ////      $revision = !isset($revision_id) ? $storage->load($node_entity_id) : $storage->loadRevision($revision_id);
  ////      $entity = $revision->getTranslation($langcode);
  //      $links['advertiser'] = static::buildLinks(Advertiser::load($advertiser_entity_id), $view_mode);
  ////
  ////      // Allow other modules to alter the node links.
  ////      $hook_context = [
  ////        'view_mode' => $view_mode,
  ////        'langcode' => $langcode,
  ////      ];
  ////      \Drupal::moduleHandler()
  ////        ->alter('node_links', $links, $entity, $hook_context);
  ////    }
  //    return $links;
  //  }

  //  protected static function buildLinks($entity, $view_mode) {
  //    $links = [];
  //
  //    // Always display a read more link on teasers because we have no way
  //    // to know when a teaser view is different than a full view.
  ////    if ($view_mode == 'teaser') {
  ////      $node_title_stripped = strip_tags($entity->label());
  ////      $links['node-readmore'] = [
  ////        'title' => t('Read more<span class="visually-hidden"> about @title</span>', [
  ////          '@title' => $node_title_stripped,
  ////        ]),
  ////        'url' => $entity->toUrl(),
  ////        'language' => $entity->language(),
  ////        'attributes' => [
  ////          'rel' => 'tag',
  ////          'title' => $node_title_stripped,
  ////        ],
  ////      ];
  ////    }
  //
  //    return [
  //      '#theme' => 'links__node__node',
  //      '#links' => $links,
  //      '#attributes' => ['class' => ['links', 'inline']],
  //    ];
  //  }

  //  public static function trustedCallbacks(): array {
  //    $callbacks = parent::trustedCallbacks();
  //    $callbacks[] = 'renderLinks';
  //    return $callbacks;
  //  }

}