<?php


/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function azure_content_theme_suggestions_block_alter(array &$suggestions, array $variables): void {
  if ($variables['elements']['#plugin_id'] === 'system_main_block') {
//    $suggestions[] = 'block__system_azure_main_content';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function azure_content_theme_registry_alter(&$theme_registry) {
  $theme_registry['block__system_azure_main_content'] = $theme_registry['block'];
  $theme_registry['block__system_azure_main_content']['path'] = \Drupal::service('extension.list.module')
      ->getPath('azure_content') . '/templates/';
  $theme_registry['block__system_azure_main_content']['template'] = str_replace('_', '-', 'block__system_azure_main_content');
}
